SCREEN_WIDTH: int = 1280
SCREEN_HEIGHT: int = 720

ASTEROID_MIN_RADIUS: int = 20
ASTEROID_KINDS: int = 3
ASTEROID_SPAWN_RATE: float = 0.8  # seconds
ASTEROID_MAX_RADIUS: int = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS: int = 20
PLAYER_TURN_SPEED: int = 300
PLAYER_SPEED: int = 200
PLAYER_BOOST_SPEED: int = 200

SHOT_RADIUS: int = 5
PLAYER_SHOT_SPEED: int = 500
PLAYER_SHOOT_COOLDOWN: float = 0.3  # seconds

PLAYER_SCATTER_SHOT_SPEED: int = 1000
PLAYER_SCATTER_SHOT_COOLDOWN: float = 1  # seconds
