SCREEN_WIDTH: int = 1280
SCREEN_HEIGHT: int = 720

ASTEROID_MIN_RADIUS: int = 20
ASTEROID_KINDS: int = 3
ASTEROID_SPAWN_RATE: float = 0.8
ASTEROID_MAX_RADIUS: int = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS: int = 20
PLAYER_TURN_SPEED: int = 300
PLAYER_SPEED: int = 200
PLAYER_TELEPORT_COOLDOWN: int = 1

ALIEN_RADIUS: int = 15
ALIEN_TURN_SPEED: int = 300
ALIEN_SPEED: int = 200
ALIEN_SPAWN_RATE: int = 5

SHOT_RADIUS: int = 5
PLAYER_SHOT_SPEED: int = 500
PLAYER_SHOOT_COOLDOWN: float = 0.20

MINE_RADIUS: int = 10
PLAYER_MINE_COOLDOWN: int = 2

PLAYER_SCATTER_SHOT_SPEED: int = 1000
PLAYER_SCATTER_SHOT_COOLDOWN: float = 0.8

SHIELD_RADIUS: int = 60
PLAYER_SHIELD_COOLDOWN: float = 10
